export type CebuCity = {
  name: string;
  postalCode: string;
};

export type BarangayEntry = {
  city: string;
  postalCode: string;
};

export const CEBU_CITIES: CebuCity[] = [
  // Cebu City
  { name: 'Cebu City', postalCode: '6000' },
  // Component Cities
  { name: 'Lapu-Lapu City', postalCode: '6015' },
  { name: 'Mandaue City', postalCode: '6014' },
  { name: 'Carcar City', postalCode: '6019' },
  { name: 'Danao City', postalCode: '6004' },
  { name: 'Naga City', postalCode: '6037' },
  { name: 'Talisay City', postalCode: '6045' },
  { name: 'Toledo City', postalCode: '6038' },
  // Municipalities
  { name: 'Alcantara', postalCode: '6028' },
  { name: 'Alcoy', postalCode: '6033' },
  { name: 'Alegria', postalCode: '6031' },
  { name: 'Aloguinsan', postalCode: '6022' },
  { name: 'Argao', postalCode: '6021' },
  { name: 'Asturias', postalCode: '6013' },
  { name: 'Badian', postalCode: '6031' },
  { name: 'Balamban', postalCode: '6044' },
  { name: 'Bantayan', postalCode: '6054' },
  { name: 'Barili', postalCode: '6036' },
  { name: 'Bogo', postalCode: '6010' },
  { name: 'Boljoon', postalCode: '6034' },
  { name: 'Borbon', postalCode: '6008' },
  { name: 'Carmen', postalCode: '6005' },
  { name: 'Catmon', postalCode: '6007' },
  { name: 'Compostela', postalCode: '6003' },
  { name: 'Consolacion', postalCode: '6001' },
  { name: 'Cordova', postalCode: '6017' },
  { name: 'Daanbantayan', postalCode: '6011' },
  { name: 'Dalaguete', postalCode: '6023' },
  { name: 'Dumanjug', postalCode: '6027' },
  { name: 'Ginatilan', postalCode: '6032' },
  { name: 'Liloan', postalCode: '6002' },
  { name: 'Madridejos', postalCode: '6055' },
  { name: 'Malabuyoc', postalCode: '6030' },
  { name: 'Medellin', postalCode: '6012' },
  { name: 'Minglanilla', postalCode: '6046' },
  { name: 'Moalboal', postalCode: '6032' },
  { name: 'Oslob', postalCode: '6025' },
  { name: 'Pilar', postalCode: '6054' },
  { name: 'Pinamungajan', postalCode: '6039' },
  { name: 'Poro', postalCode: '6053' },
  { name: 'Ronda', postalCode: '6029' },
  { name: 'Samboan', postalCode: '6026' },
  { name: 'San Fernando', postalCode: '6018' },
  { name: 'San Francisco', postalCode: '6052' },
  { name: 'San Remigio', postalCode: '6009' },
  { name: 'Santa Fe', postalCode: '6054' },
  { name: 'Santander', postalCode: '6035' },
  { name: 'Sibonga', postalCode: '6020' },
  { name: 'Sogod', postalCode: '6006' },
  { name: 'Tabogon', postalCode: '6009' },
  { name: 'Tabuelan', postalCode: '6043' },
  { name: 'Tuburan', postalCode: '6042' },
  { name: 'Tudela', postalCode: '6053' },
];

export const POSTAL_CODE_MAP: Record<string, string> = Object.fromEntries(
  CEBU_CITIES.map((c) => [c.name, c.postalCode]),
);

// Barangay → { city, postalCode } lookup
// Keys are lowercase for case-insensitive matching
export const BARANGAY_MAP: Record<string, BarangayEntry> = {
  // ── Cordova ──────────────────────────────────────────────
  'alegria': { city: 'Cordova', postalCode: '6017' },
  'bangbang': { city: 'Cordova', postalCode: '6017' },
  'buagsong': { city: 'Cordova', postalCode: '6017' },
  'catarman': { city: 'Cordova', postalCode: '6017' },
  'cogon': { city: 'Cordova', postalCode: '6017' },
  'dapitan': { city: 'Cordova', postalCode: '6017' },
  'day-as': { city: 'Cordova', postalCode: '6017' },
  'gabi': { city: 'Cordova', postalCode: '6017' },
  'gilutongan': { city: 'Cordova', postalCode: '6017' },
  'ibabao': { city: 'Cordova', postalCode: '6017' },
  'pilipog': { city: 'Cordova', postalCode: '6017' },
  'san miguel': { city: 'Cordova', postalCode: '6017' },

  // ── Cebu City ─────────────────────────────────────────────
  'adlaon': { city: 'Cebu City', postalCode: '6000' },
  'agsungot': { city: 'Cebu City', postalCode: '6000' },
  'apas': { city: 'Cebu City', postalCode: '6000' },
  'bacayan': { city: 'Cebu City', postalCode: '6000' },
  'banilad': { city: 'Cebu City', postalCode: '6000' },
  'basak pardo': { city: 'Cebu City', postalCode: '6000' },
  'basak san nicolas': { city: 'Cebu City', postalCode: '6000' },
  'binaliw': { city: 'Cebu City', postalCode: '6000' },
  'bonbon': { city: 'Cebu City', postalCode: '6000' },
  'budlaan': { city: 'Cebu City', postalCode: '6000' },
  'busay': { city: 'Cebu City', postalCode: '6000' },
  'calamba': { city: 'Cebu City', postalCode: '6000' },
  'camputhaw': { city: 'Cebu City', postalCode: '6000' },
  'capitol site': { city: 'Cebu City', postalCode: '6000' },
  'carreta': { city: 'Cebu City', postalCode: '6000' },
  'cashbah': { city: 'Cebu City', postalCode: '6000' },
  'kasambagan': { city: 'Cebu City', postalCode: '6000' },
  'cogon pardo': { city: 'Cebu City', postalCode: '6000' },
  'cogon ramos': { city: 'Cebu City', postalCode: '6000' },
  'duljo fatima': { city: 'Cebu City', postalCode: '6000' },
  'ermita': { city: 'Cebu City', postalCode: '6000' },
  'guadalupe': { city: 'Cebu City', postalCode: '6000' },
  'guba': { city: 'Cebu City', postalCode: '6000' },
  'hippodromo': { city: 'Cebu City', postalCode: '6000' },
  'inayawan': { city: 'Cebu City', postalCode: '6000' },
  'kalubihan': { city: 'Cebu City', postalCode: '6000' },
  'kalunasan': { city: 'Cebu City', postalCode: '6000' },
  'kamagayan': { city: 'Cebu City', postalCode: '6000' },
  'labangon': { city: 'Cebu City', postalCode: '6000' },
  'lahug': { city: 'Cebu City', postalCode: '6000' },
  'lorega': { city: 'Cebu City', postalCode: '6000' },
  'lusaran': { city: 'Cebu City', postalCode: '6000' },
  'luz': { city: 'Cebu City', postalCode: '6000' },
  'mabini': { city: 'Cebu City', postalCode: '6000' },
  'mabolo': { city: 'Cebu City', postalCode: '6000' },
  'malubog': { city: 'Cebu City', postalCode: '6000' },
  'mambaling': { city: 'Cebu City', postalCode: '6000' },
  'nivel hills': { city: 'Cebu City', postalCode: '6000' },
  'non-stock': { city: 'Cebu City', postalCode: '6000' },
  'north reclamation area': { city: 'Cebu City', postalCode: '6000' },
  'od-og': { city: 'Cebu City', postalCode: '6000' },
  'pardo': { city: 'Cebu City', postalCode: '6000' },
  'pari-an': { city: 'Cebu City', postalCode: '6000' },
  'pasil': { city: 'Cebu City', postalCode: '6000' },
  'pit-os': { city: 'Cebu City', postalCode: '6000' },
  'poblacion pardo': { city: 'Cebu City', postalCode: '6000' },
  'pulangbato': { city: 'Cebu City', postalCode: '6000' },
  'pung-ol sibugay': { city: 'Cebu City', postalCode: '6000' },
  'punta princesa': { city: 'Cebu City', postalCode: '6000' },
  'quiot pardo': { city: 'Cebu City', postalCode: '6000' },
  'sambag i': { city: 'Cebu City', postalCode: '6000' },
  'sambag ii': { city: 'Cebu City', postalCode: '6000' },
  'san antonio': { city: 'Cebu City', postalCode: '6000' },
  'san jose': { city: 'Cebu City', postalCode: '6000' },
  'san nicolas central': { city: 'Cebu City', postalCode: '6000' },
  'san roque': { city: 'Cebu City', postalCode: '6000' },
  'santa cruz': { city: 'Cebu City', postalCode: '6000' },
  'santo nino': { city: 'Cebu City', postalCode: '6000' },
  'sapangdaku': { city: 'Cebu City', postalCode: '6000' },
  'sawang calero': { city: 'Cebu City', postalCode: '6000' },
  'sinsin': { city: 'Cebu City', postalCode: '6000' },
  'sirao': { city: 'Cebu City', postalCode: '6000' },
  'suba': { city: 'Cebu City', postalCode: '6000' },
  'sudlon i': { city: 'Cebu City', postalCode: '6000' },
  'sudlon ii': { city: 'Cebu City', postalCode: '6000' },
  't. padilla': { city: 'Cebu City', postalCode: '6000' },
  'talamban': { city: 'Cebu City', postalCode: '6000' },
  'taptap': { city: 'Cebu City', postalCode: '6000' },
  'tejero': { city: 'Cebu City', postalCode: '6000' },
  'tinago': { city: 'Cebu City', postalCode: '6000' },
  'to-ong pardo': { city: 'Cebu City', postalCode: '6000' },
  'tuburan': { city: 'Cebu City', postalCode: '6000' },
  'tisa': { city: 'Cebu City', postalCode: '6000' },

  // ── Lapu-Lapu City ────────────────────────────────────────
  'agus': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'babag': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'bankal': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'baring': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'basak': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'buaya': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'calawisan': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'canjulao': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'caw-oy': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'caubian': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'gun-ob': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'ibo': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'looc': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'mactan': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'maribago': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'marigondon': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'pajac': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'pajo': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'pakna-an': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'poblacion': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'punta engano': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'pusok': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'sabang': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'santa rosa': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'subabasbas': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'talima': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'tingo': { city: 'Lapu-Lapu City', postalCode: '6015' },
  'tungasan': { city: 'Lapu-Lapu City', postalCode: '6015' },

  // ── Mandaue City ──────────────────────────────────────────
  'alang-alang': { city: 'Mandaue City', postalCode: '6014' },
  'bakilid': { city: 'Mandaue City', postalCode: '6014' },
  'banilad mandaue': { city: 'Mandaue City', postalCode: '6014' },
  'cabancalan': { city: 'Mandaue City', postalCode: '6014' },
  'cambaro': { city: 'Mandaue City', postalCode: '6014' },
  'canduman': { city: 'Mandaue City', postalCode: '6014' },
  'casili': { city: 'Mandaue City', postalCode: '6014' },
  'casuntingan': { city: 'Mandaue City', postalCode: '6014' },
  'centro': { city: 'Mandaue City', postalCode: '6014' },
  'cubacub': { city: 'Mandaue City', postalCode: '6014' },
  'guizo': { city: 'Mandaue City', postalCode: '6014' },
  'ibabao-estancia': { city: 'Mandaue City', postalCode: '6014' },
  'jagobiao': { city: 'Mandaue City', postalCode: '6014' },
  'labogon': { city: 'Mandaue City', postalCode: '6014' },
  'looc mandaue': { city: 'Mandaue City', postalCode: '6014' },
  'maguikay': { city: 'Mandaue City', postalCode: '6014' },
  'mantuyong': { city: 'Mandaue City', postalCode: '6014' },
  'opao': { city: 'Mandaue City', postalCode: '6014' },
  'pagsabungan': { city: 'Mandaue City', postalCode: '6014' },
  'pakna-an mandaue': { city: 'Mandaue City', postalCode: '6014' },
  'paknaan': { city: 'Mandaue City', postalCode: '6014' },
  'subangdaku': { city: 'Mandaue City', postalCode: '6014' },
  'tabok': { city: 'Mandaue City', postalCode: '6014' },
  'tawason': { city: 'Mandaue City', postalCode: '6014' },
  'tingub': { city: 'Mandaue City', postalCode: '6014' },
  'tipolo': { city: 'Mandaue City', postalCode: '6014' },
  'umapad': { city: 'Mandaue City', postalCode: '6014' },

  // ── Talisay City ──────────────────────────────────────────
  'biasong': { city: 'Talisay City', postalCode: '6045' },
  'bulacao': { city: 'Talisay City', postalCode: '6045' },
  'dumlog': { city: 'Talisay City', postalCode: '6045' },
  'jaclupan': { city: 'Talisay City', postalCode: '6045' },
  'lagtang': { city: 'Talisay City', postalCode: '6045' },
  'lawaan i': { city: 'Talisay City', postalCode: '6045' },
  'lawaan ii': { city: 'Talisay City', postalCode: '6045' },
  'lawaan iii': { city: 'Talisay City', postalCode: '6045' },
  'linao': { city: 'Talisay City', postalCode: '6045' },
  'manipis': { city: 'Talisay City', postalCode: '6045' },
  'ngeso': { city: 'Talisay City', postalCode: '6045' },
  'pooc': { city: 'Talisay City', postalCode: '6045' },
  'san isidro': { city: 'Talisay City', postalCode: '6045' },
  'tabunok': { city: 'Talisay City', postalCode: '6045' },
  'tangke': { city: 'Talisay City', postalCode: '6045' },

  // ── Consolacion ───────────────────────────────────────────
  'cabangahan': { city: 'Consolacion', postalCode: '6001' },
  'cansaga': { city: 'Consolacion', postalCode: '6001' },
  'coverage': { city: 'Consolacion', postalCode: '6001' },
  'danglag': { city: 'Consolacion', postalCode: '6001' },
  'jugan': { city: 'Consolacion', postalCode: '6001' },
  'lamac': { city: 'Consolacion', postalCode: '6001' },
  'nangka': { city: 'Consolacion', postalCode: '6001' },
  'panas': { city: 'Consolacion', postalCode: '6001' },
  'panoypoy': { city: 'Consolacion', postalCode: '6001' },
  'pitogo': { city: 'Consolacion', postalCode: '6001' },
  'sacsac': { city: 'Consolacion', postalCode: '6001' },
  'tayud': { city: 'Consolacion', postalCode: '6001' },
  'tilhaong': { city: 'Consolacion', postalCode: '6001' },
  'tolotolo': { city: 'Consolacion', postalCode: '6001' },
  'tungkop': { city: 'Consolacion', postalCode: '6001' },

  // ── Liloan ────────────────────────────────────────────────
  'cabadiangan': { city: 'Liloan', postalCode: '6002' },
  'calero': { city: 'Liloan', postalCode: '6002' },
  'ciudad': { city: 'Liloan', postalCode: '6002' },
  'cotcot': { city: 'Liloan', postalCode: '6002' },
  'jubay': { city: 'Liloan', postalCode: '6002' },
  'lataban': { city: 'Liloan', postalCode: '6002' },
  'mulao': { city: 'Liloan', postalCode: '6002' },
  'poblacion liloan': { city: 'Liloan', postalCode: '6002' },
  'san roque liloan': { city: 'Liloan', postalCode: '6002' },
  'san vicente': { city: 'Liloan', postalCode: '6002' },
  'santa cruz liloan': { city: 'Liloan', postalCode: '6002' },
  'santa filomena': { city: 'Liloan', postalCode: '6002' },
  'santiago': { city: 'Liloan', postalCode: '6002' },
  'soong': { city: 'Liloan', postalCode: '6002' },
  'yati': { city: 'Liloan', postalCode: '6002' },

  // ── Minglanilla ───────────────────────────────────────────
  'cadulawan': { city: 'Minglanilla', postalCode: '6046' },
  'calajoan': { city: 'Minglanilla', postalCode: '6046' },
  'camp 7': { city: 'Minglanilla', postalCode: '6046' },
  'camp 8': { city: 'Minglanilla', postalCode: '6046' },
  'cuanos': { city: 'Minglanilla', postalCode: '6046' },
  'guindaruhan': { city: 'Minglanilla', postalCode: '6046' },
  'linao minglanilla': { city: 'Minglanilla', postalCode: '6046' },
  'manduang': { city: 'Minglanilla', postalCode: '6046' },
  'pakigne': { city: 'Minglanilla', postalCode: '6046' },
  'tubod': { city: 'Minglanilla', postalCode: '6046' },
  'tulay': { city: 'Minglanilla', postalCode: '6046' },
  'tunghaan': { city: 'Minglanilla', postalCode: '6046' },
  'tungkil': { city: 'Minglanilla', postalCode: '6046' },
};

// Look up city + postal code from a barangay name (case-insensitive)
export function lookupBarangay(barangay: string): BarangayEntry | null {
  return BARANGAY_MAP[barangay.trim().toLowerCase()] ?? null;
}
